### ISSUE TITLE
Correct behavior of LDBr

### ISSUE THREAD

**Issue by Matthew-McRaven** [StanWarford/pep9micro#41]
According to the specification, LDBr should load a byte from meory into the lower half of the accumulator without zeroing out the upper half.

Pep9Micro does not conform to this behavior.

The current behavior of Pep9Micro is to clear the register, and then load the correct low order bit.

**Comment by Matthew-McRaven** [comment]
This should affect symbols surrounding ldba, ldbx symbols.

**Comment by StanWarford** [comment]
Yes, the most significant byte of register r is unchanged. I had to fix a bug in the app not too long ago that zeroed out the most significant byte.  You can test it in Pep/9. —jsw

**Comment by Matthew-McRaven** [comment]
Thanks for the information. I verified the behavior in Pep/9 and Pep/8, and the RTL of the LDBr instruction. The microcode was in error, and is corrected as of 60410c581a1a46ae840b1ba596b168192202d5a0.
